# Generated by Django 5.0.1 on 2025-05-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='route',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
