# Generated by Django 5.0.1 on 2025-06-04 11:37

from django.db import migrations
import uuid

def generate_unique_join_codes(apps, schema_editor):
    PharmacyProfile = apps.get_model('pharmacy', 'PharmacyProfile')
    for pharmacy in PharmacyProfile.objects.filter(join_code__isnull=True):
        pharmacy.join_code = uuid.uuid4().hex[:12].upper()
        pharmacy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_pharmacyprofile_join_code_pharmacistprofile'),
    ]

    operations = [
        migrations.RunPython(generate_unique_join_codes),
    ]
