# Generated by Django 5.0.1 on 2025-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_generate_join_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='city',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='street_address',
            field=models.CharField(default=12, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='zip_code',
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
    ]
