# Generated by Django 5.0.1 on 2025-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_remove_pharmacyprofile_address_pharmacyprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprofile',
            name='state',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
