# Generated by Django 5.0.1 on 2025-06-13 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_medicationreminder_medicine_and_more'),
        ('pharmacy', '0007_alter_prescription_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription', to='patients.patientprofile'),
        ),
    ]
