# Generated by Django 4.2.23 on 2025-10-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_alter_prescription_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='refills_left',
            field=models.IntegerField(default=3),
        ),
    ]
