# Generated by Django 4.2.23 on 2025-10-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_prescription_refills_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='reffil_pending',
            field=models.BooleanField(default=False),
        ),
    ]
