# Generated by Django 4.2.23 on 2025-10-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_prescription_reffil_pending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='reffil_pending',
            new_name='refill_pending',
        ),
    ]
