# Generated by Django 4.2.23 on 2025-10-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_rename_reffil_pending_prescription_refill_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='refilled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
