# Generated by Django 4.2.23 on 2025-10-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_prescription_refilled_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='resupply_pending',
            field=models.BooleanField(default=False),
        ),
    ]
