# Generated by Django 4.2.23 on 2025-12-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_drug_resupply_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='pharmacy.pharmacyprofile'),
        ),
        migrations.AddField(
            model_name='drug',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20),
        ),
    ]
