# Generated by Django 4.2.23 on 2025-12-28 14:42

from django.db import migrations


def duplicate_drugs_for_pharmacies(apps, schema_editor):
    """
    Duplicate all existing drugs for each pharmacy.
    Woodlands pharmacy keeps its current stock, all others get stock=100.
    """
    Drug = apps.get_model('pharmacy', 'Drug')
    PharmacyProfile = apps.get_model('pharmacy', 'PharmacyProfile')
    Prescription = apps.get_model('pharmacy', 'Prescription')

    # Get all existing drugs (with no pharmacy assigned)
    existing_drugs = list(Drug.objects.filter(pharmacy__isnull=True))

    if not existing_drugs:
        return  # No drugs to duplicate

    # Get all pharmacies
    pharmacies = PharmacyProfile.objects.all()

    # Create a mapping from old drug ID to new drug IDs per pharmacy
    drug_mapping = {}  # {old_drug_id: {pharmacy_id: new_drug_id}}

    # For each pharmacy, create copies of all drugs
    for pharmacy in pharmacies:
        is_woodlands = pharmacy.pharmacy_name == "Woodlands"

        for drug in existing_drugs:
            # Determine stock level
            stock = drug.stock if is_woodlands else 100

            # Determine status based on stock
            if stock == 0:
                status = 'out_of_stock'
            elif stock <= 30:
                status = 'low_stock'
            else:
                status = 'in_stock'

            # Create new drug for this pharmacy
            new_drug = Drug.objects.create(
                pharmacy=pharmacy,
                name=drug.name,
                brand=drug.brand,
                description=drug.description,
                dosage=drug.dosage,
                route=drug.route,
                stock=stock,
                status=status,
                resupply_pending=False  # Reset resupply pending for new copies
            )

            # Track the mapping
            if drug.id not in drug_mapping:
                drug_mapping[drug.id] = {}
            drug_mapping[drug.id][pharmacy.id] = new_drug.id

    # Update all prescriptions to point to the correct pharmacy-specific drug
    for prescription in Prescription.objects.all():
        old_drug_id = prescription.medicine_id

        # Get the patient's pharmacy
        if prescription.patient and prescription.patient.pharmacy_id:
            pharmacy_id = prescription.patient.pharmacy_id

            # Update to the new drug for this pharmacy
            if old_drug_id in drug_mapping and pharmacy_id in drug_mapping[old_drug_id]:
                prescription.medicine_id = drug_mapping[old_drug_id][pharmacy_id]
                prescription.save()

    # Delete the old drugs that had no pharmacy assigned
    Drug.objects.filter(pharmacy__isnull=True).delete()


def reverse_migration(apps, schema_editor):
    """
    This reverse migration cannot restore the exact previous state,
    but we'll keep one copy of each drug (from the first pharmacy).
    """
    Drug = apps.get_model('pharmacy', 'Drug')
    PharmacyProfile = apps.get_model('pharmacy', 'PharmacyProfile')

    # Get the first pharmacy
    first_pharmacy = PharmacyProfile.objects.first()
    if not first_pharmacy:
        return

    # Get all unique drug names
    unique_drugs = Drug.objects.values('name', 'brand').distinct()

    # For each unique drug, keep only the one from the first pharmacy
    for drug_info in unique_drugs:
        drug = Drug.objects.filter(
            name=drug_info['name'],
            brand=drug_info['brand'],
            pharmacy=first_pharmacy
        ).first()

        if drug:
            # Set pharmacy to null for this one drug
            drug.pharmacy = None
            drug.save()

            # Delete all other copies
            Drug.objects.filter(
                name=drug_info['name'],
                brand=drug_info['brand']
            ).exclude(id=drug.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_drug_pharmacy_drug_status'),
    ]

    operations = [
        migrations.RunPython(duplicate_drugs_for_pharmacies, reverse_migration),
    ]
