# Generated by Django 5.0.1 on 2025-06-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaccount',
            name='role',
            field=models.CharField(choices=[('pharmacy admin', 'Pharmacy Admin'), ('pharmacist', 'Pharmacist'), ('patient', 'Patient')], max_length=20),
        ),
    ]
