# Generated by Django 5.0.1 on 2025-08-03 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notifications'),
        ('patients', '0017_medicationreminder_restoration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='patients.medicationreminder'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.message'),
        ),
    ]
