# Generated by Django 4.2.23 on 2025-08-30 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_thread_alter_message_read_time_message_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='accounts.thread'),
            preserve_default=False,
        ),
    ]
