# Generated by Django 4.2.23 on 2025-08-30 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_message_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='participant',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.thread'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
