# Generated by Django 4.2.23 on 2025-10-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_message_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaccount',
            name='role',
            field=models.CharField(choices=[('pharmacy admin', 'Pharmacy Admin'), ('pharmacist', 'Pharmacist'), ('patient', 'Patient'), ('system', 'System')], max_length=20),
        ),
    ]
