# Generated by Django 4.2.23 on 2025-10-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customaccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('stock', 'Stock'), ('refill', 'Refill'), ('message', 'Message')], default='message', max_length=20),
        ),
    ]
