# Generated by Django 4.2.23 on 2025-10-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_message_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.AddField(
            model_name='message',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
