# Generated by Django 4.2.23 on 2025-10-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_message_message_type_message_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_refill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='prescription_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
