# Generated by Django 4.2.23 on 2025-10-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_message_is_refill_message_prescription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_refill',
        ),
        migrations.RemoveField(
            model_name='message',
            name='prescription_id',
        ),
    ]
