# Generated by Django 4.2.23 on 2025-10-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_message_is_refill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='refill_fulfilled',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
