# Generated by Django 4.2.23 on 2025-10-16 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_rename_reffil_pending_prescription_refill_pending'),
        ('accounts', '0016_message_refill_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.prescription'),
        ),
    ]
