# Generated by Django 4.2.23 on 2025-10-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_drug_resupply_pending'),
        ('accounts', '0017_message_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug'),
        ),
        migrations.AddField(
            model_name='message',
            name='resupply_fulfilled',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
