# Generated by Django 4.2.23 on 2025-11-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_message_read_remove_message_read_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readstatus',
            name='read_time',
        ),
    ]
