# Generated by Django 4.2.23 on 2025-11-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0013_drug_resupply_pending'),
        ('accounts', '0021_remove_readstatus_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.prescription'),
        ),
    ]
