# Generated by Django 4.2.23 on 2025-12-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_notifications_content_notifications_drug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
