# Generated by Django 5.0.1 on 2025-06-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_pharmacist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacist',
            old_name='Pharmacist',
            new_name='pharmacist',
        ),
    ]
