# Generated by Django 5.0.1 on 2025-06-04 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientpharmacy_delete_pharmacist'),
        ('pharmacy', '0003_pharmacyprofile_join_code_pharmacistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='first_name',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_name',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientpharmacy',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='pharmacy.pharmacyprofile'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
