# Generated by Django 5.0.1 on 2025-06-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patientprofile_first_name_patientprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
