# Generated by Django 5.0.1 on 2025-06-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patientprofile_first_name_and_more'),
        ('pharmacy', '0006_pharmacyprofile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationreminder',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='medicationreminder',
            name='patient',
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='prescription',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.prescription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='pharmacy.pharmacyprofile'),
        ),
        migrations.DeleteModel(
            name='PatientPharmacy',
        ),
    ]
