# Generated by Django 5.0.1 on 2025-07-08 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_medicationreminder_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreminder',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile'),
            preserve_default=False,
        ),
    ]
