# Generated by Django 5.0.1 on 2025-07-12 11:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_medicationreminder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationreminder',
            name='time',
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='ReminderTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='patients.medicationreminder')),
            ],
        ),
    ]
