# Generated by Django 5.0.1 on 2025-07-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_remove_medicationreminder_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationreminder',
            name='frequency',
            field=models.IntegerField(choices=[(1, '1 time(s)'), (2, '2 time(s)'), (3, '3 time(s)'), (4, '4 time(s)'), (5, '5 time(s)')]),
        ),
    ]
