# Generated by Django 5.0.1 on 2025-07-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_medicationreminder_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreminder',
            name='day_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='frequency',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
