# Generated by Django 5.0.1 on 2025-07-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_medicationreminder_day_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationreminder',
            name='day_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='frequency',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
