# Generated by Django 5.0.1 on 2025-07-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_medicationreminder_day_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindertime',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
