# Generated by Django 5.0.1 on 2025-07-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_remindertime_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreminder',
            name='remaining_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
