# Generated by Django 5.0.1 on 2025-07-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_medicationreminder_remaining_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreminder',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
