# Generated by Django 5.0.1 on 2025-08-03 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_medicationreminder_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreminder',
            name='restoration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
