# Generated by Django 4.2.23 on 2025-08-10 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_medicationreminder_restoration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationreminder',
            name='day_amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
