# Generated by Django 4.2.23 on 2025-08-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_alter_medicationreminder_day_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindertime',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
